version: "3.3"
services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    restart: always
    ports:
      - "8080:8080"
